config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: { registrations: 'users/registrations', sessions: 'users/sessions' }
  root to: 'pages#home'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  
  #APP 
  resources :juniors do 
    
    get '/sign_up_step2', to: 'adherents#signup_step2', as: 'signup_step2'
    resources :membre_requests
    
    resources :generated_documents

    resources :membres do
      resources :mandat_requests
      resources :mandats
    end

    resources :etudes do
      resources :phases do
        resources :document_phases
        resources :selection_intervenants, except: :index do
          resources :postulants do
            resources :document_postulants
          end
        end
        resources :intervenants do
          resources :document_intervenants
        end
      end
      resources :document_etudes
    end

    resources :selection_intervenants, only: :index do
      resources :postulants, only: :create
    end

    get '/mes_missions', to: 'selection_intervenants#mes_missions', as: 'mes_missions'
    get '/update_mode', to: 'juniors#update_mode', as: 'update_mode'

    resources :clients
    resources :adherents do
      resources :document_adherents
    end

    resources :junior_configurations do
      resources :config_doc_adherents
      resources :config_doc_etudes
      resources :poles
      resources :postes
      resources :permissions
      resources :prestations
      get '/archives', to: 'junior_configurations#archives', as: 'archives'
    end

    resources :tresoreries

    resources :user do
      resources :adherents do
        resources :document_adhesions
      end
    end
  end

  #API V1
  namespace :api, defaults: { format: :json } do
    namespace :v1 do
      resources :etudes, only: [ :index, :show, :update ]
      get '/sessions', to: 'sessions#index', as: 'session'
      get '/userparams', to: 'userparams#index', as: 'userparam'
      get '/userparams/:id', to: 'userparams#update'
    end
  end

  # Sidekiq
  require "sidekiq/web"
  authenticate :user, ->(user) { user.admin? } do
    mount Sidekiq::Web => '/sidekiq'
  end
end

app/models/adherent.rb
class Adherent < ApplicationRecord
  belongs_to :user
  has_many :document_adhesions, dependent: :destroy
  has_many :document_adherents, dependent: :destroy

  has_one_attached :avatar
  delegate :junior, to: :user
end

app/models/client.rb
class Client < ApplicationRecord
  belongs_to :junior
end

app/models/config_doc_etude.rb
class ConfigDocEtude < ApplicationRecord
  belongs_to :junior_configuration

  has_one_attached :document_type
end

app/models/document_etude.rb
class DocumentEtude < ApplicationRecord
  belongs_to :etude

  has_one_attached :document
  has_one_attached :generated_document
end

app/models/document_phase.rb
class DocumentPhase < ApplicationRecord
  belongs_to :phase

  has_one_attached :document
  has_one_attached :generated_document
end

app/models/etude.rb
class Etude < ApplicationRecord
  belongs_to :client, optional: true
  belongs_to :prestation
  belongs_to :charge_etude, class_name: 'User'
  belongs_to :charge_qualite, class_name: 'User', optional: true
  belongs_to :charge_rh, class_name: 'User', optional: true
  belongs_to :junior

  has_many :phases, dependent: :destroy
  has_many :document_etudes, dependent: :destroy
end

app/models/intervenant.rb
class Intervenant < ApplicationRecord
  belongs_to :phase
  belongs_to :user

  has_many :document_intervenants, dependent: :destroy
end

app/models/junior.rb
class Junior < ApplicationRecord
  validates_presence_of :codeje, on: :create, message: "Vous devez avoir un code"
  validates_uniqueness_of :codeje, on: :create, message: "Ce code ne peut être utilisé"

  has_many :users, dependent: :destroy
  has_many :membre_requests, dependent: :destroy
  has_many :membres, through: :membre_requests
  has_many :adherents, through: :users
  has_many :clients, dependent: :destroy
  has_many :etudes, dependent: :destroy
  has_many :phases, through: :etudes

  has_one :junior_configuration
  has_many :config_doc_adherents, through: :junior_configuration
  has_many :poles, through: :junior_configuration
  has_many :postes, through: :junior_configuration
  has_many :permissions, through: :junior_configuration
end

app/models/mandat.rb
class Mandat < ApplicationRecord
  belongs_to :mandat_request
  belongs_to :permission
end

app/models/mandat_request.rb
class MandatRequest < ApplicationRecord
  belongs_to :poste
  belongs_to :pole
  belongs_to :membre

  has_one :mandat, dependent: :destroy
end

app/models/membre.rb
class Membre < ApplicationRecord
  belongs_to :membre_request
  delegate :user, to: :membre_request, allow_nil: true

  has_many :mandat_requests, dependent: :destroy
  has_many :mandats, through: :mandat_requests
  has_many :permissions, through: :mandats
end

app/models/membre_request.rb
class MembreRequest < ApplicationRecord
  belongs_to :junior
  belongs_to :user
  has_one :membre, dependent: :destroy
end

app/models/permission.rb
class Permission < ApplicationRecord
  belongs_to :junior_configuration
end

app/models/phase.rb
class Phase < ApplicationRecord
  belongs_to :etude

  has_one :selection_intervenant, dependent: :destroy
  has_many :intervenants, dependent: :destroy

  has_many :document_phases, dependent: :destroy
end

app/models/pole.rb
class Pole < ApplicationRecord
  belongs_to :junior_configuration
end

app/models/poste.rb
class Poste < ApplicationRecord
  belongs_to :junior_configuration
end

app/models/postulant.rb
class Postulant < ApplicationRecord
  belongs_to :selection_intervenant
  belongs_to :user

  has_many :document_postulants, dependent: :destroy
end

app/models/prestation.rb
class Prestation < ApplicationRecord
  belongs_to :junior_configuration
end

app/models/tresorerie.rb
class Tresorerie < ApplicationRecord
  belongs_to :junior
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  acts_as_token_authenticatable

  belongs_to :junior

  has_one :membre_request, dependent: :destroy
  has_one :userparam, dependent: :destroy
  has_one :membre, through: :membre_request
  has_many :mandat_requests, through: :membre
  has_many :mandats, through: :mandat_requests
  has_many :permissions, through: :mandats
  has_one :adherent, dependent: :destroy
  has_one :document_adhesion, through: :adherent
  has_many :postulants, dependent: :destroy
  has_many :intervenants, dependent: :destroy
end

app/models/userparam.rb
class Userparam < ApplicationRecord
  belongs_to :user
end

app/controllers/membres_controller.rb
class MembresController < ApplicationController
  before_action :authenticate_user!

  def index
    @junior = Junior.find(junior_id_params.to_i)
    @membres = policy_scope(Membre)
    @request_membres = policy_scope(MembreRequest)
    @request_mandats = policy_scope(MandatRequest)
  end

  private

  def junior_id_params
    params.require(:junior_id)
  end
end

app/views/membres/index.html.erb
<div class="menu">
  <div class="tabs">
    <div class="tab active">Membres</div>
    <div class="tab">Demandes en Attente</div>
    <div class="tab">Demandes de mandats</div>
  </div>
  <div class="contents">
    <% # Menu 1 %>
    <div class="content active">
      <div class="cards-profile">
        <% @membres.each do |membre| %>
          <div class="card">
            <div class="avatar"><%= membre.membre_request.user.adherent.avatar.url.nil? ? image_tag("logo_hex.png", class: 'avatar') : image_tag(membre.membre_request.user.adherent.avatar.variant(resize_to_limit: [500, 500]), class: 'avatar') %></div>
            <div class="contenu">
              <div class="title">
                <div><%= membre.membre_request.user.adherent.prenom %></div>
                <div><%= membre.membre_request.user.adherent.nom %></div>
              </div>
              <div class="main">
                <div></div>
                  <% mandats_en_cours = membre.mandat_requests.where(status: 'approved').where('date_debut < ?', Date.today).where('Date_fin > ?', Date.today) %>
                  <% if !mandats_en_cours.count.zero? %>
                    <div>Poste : <%= mandats_en_cours.first.poste.nom %></div>
                    <div>Pole : <%= mandats_en_cours.first.pole.nom %></div>
                  <% else %>
                    <div class="invalid">Aucun mandat en cours</div>
                  <% end %>
                <div></div>
              </div>
              <div class="comment">
                <% if membre.membre_request.user.adherent.file_status == 'valid' %>
                    <div class="valid">Dossier valide</div>
                <% elsif membre.membre_request.user.adherent.file_status == 'invalid' %>
                    <div class="invalid">Dossier invalide</div>
                <% elsif membre.membre_request.user.adherent.file_status == 'pending' %>
                    <div class="pending">En attente de validation</div>
                <% end %>
              </div>
            </div>
          </div>
        <% end %>
      </div>
    </div>

    <% # Menu 2 %>
    <div class="content">
      <div class="cards-profile">
        <% @request_membres.where(status: 'pending').each do |request| %>
          <div class="card">
            <div class="avatar"><%= request.user.adherent.avatar.url.nil? ? image_tag("logo_hex.png", class: 'avatar') : image_tag(request.user.adherent.avatar.variant(resize_to_limit: [500, 500]), class: 'avatar') %></div>
            <div class="contenu">
              <div class="title">
                <div><%= request.user.adherent.prenom %></div>
                <div><%= request.user.adherent.nom %></div>
              </div>
              <div class="main">
                <div></div>
                <div></div>
              </div>
              <div class="comment">
                <% if request.user.adherent.file_status == 'valid' %>
                    <div class="valid">Dossier valide</div>
                <% elsif request.user.adherent.file_status == 'invalid' %>
                    <div class="invalid">Dossier invalide</div>
                <% elsif request.user.adherent.file_status == 'pending' %>
                    <div class="pending">En attente de validation</div>
                <% end %>
              </div>
              <div class="actions">
                <%= link_to junior_membre_request_path(request.junior_id, request.id, membre_request: {status: 'approved'}), method: 'patch' do %>
                  <div class="action" style="color: var(--vert);">
                    <i class="fas fa-check"></i>
                  </div>
                <% end %>
                <%= link_to junior_membre_request_path(request.junior_id, request.id), method: :delete do %>
                  <div class="action" style="color: var(--rouge);">
                    <i class="fas fa-times"></i>
                  </div>
                <% end %>
              </div>
            </div>
          </div>
        <% end %>
      </div>
    </div>

    <% #raise %>
    <% # Menu 3 %>
    <div class="content">
      <div class="cards-profile">
        <% @request_mandats.where(status: 'pending').each do |request| %>
          <%= simple_form_for [@junior, request.membre, request] do |f| %>
            <div class="card">
            <div class="avatar"><%= request.membre.membre_request.user.adherent.avatar.url.nil? ? image_tag("logo_hex.png", class: 'avatar') : image_tag(request.membre.membre_request.user.adherent.avatar.variant(resize_to_limit: [500, 500]), class: 'avatar') %></div>
              <div class="contenu">
                <div class="title">
                  <div><%= request.membre.membre_request.user.adherent.prenom %></div>
                  <div><%= request.membre.membre_request.user.adherent.nom %></div>
                </div>
                <div class="main">
                  <div>Poste : <%= request.poste.nom %></div>
                  <div>Pole : <%= request.pole.nom %></div>
                  <div>Du <%= request.date_debut.strftime("%d/%m/%Y") %> au <%= request.date_fin.strftime("%d/%m/%Y") %></div>
                </div>
                <div class="comment">
                <%= simple_fields_for :permission do |n| %>
                  <div class="formulaire">
                    <div class="input">
                    <%= n.input :id, autofocus: true, required: true, label: "Autorisation :", collection: @junior.junior_configuration.permissions, :label_method => lambda { |autorisation| "#{autorisation.nom}" } %>
                    </div>
                  </div>
                <% end %>
                <%= f.hidden_field :status, value: "approved" %>
                </div>
                <% #raise %>
                <div class="actions">
                  <%= button_tag type: 'submit' do %>
                    <div class="action" style="color: var(--vert);">
                      <i class="fas fa-check"></i>
                    </div>
                  <% end %>
                  <%= button_tag(:type => 'button') do %>
                    <%= link_to junior_membre_mandat_request_path(request.membre.membre_request.junior_id, request.membre.membre_request.id, request.id), method: :delete do %>
                      <div class="action" style="color: var(--rouge);">
                        <i class="fas fa-times"></i>
                      </div>
                    <% end %>
                  <% end %>
                </div>
              </div>
            </div>
          <% end %>  
        <% end %>
      </div>
    </div>
  </div>
</div>