config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: { registrations: 'users/registrations', sessions: 'users/sessions' }
  root to: 'pages#home'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  
  #APP 
  resources :juniors do 
    
    get '/sign_up_step2', to: 'adherents#signup_step2', as: 'signup_step2'
    resources :membre_requests
    
    resources :generated_documents

    resources :membres do
      resources :mandat_requests
      resources :mandats
    end

    resources :etudes do
      resources :phases do
        resources :document_phases
        resources :selection_intervenants, except: :index do
          resources :postulants do
            resources :document_postulants
          end
        end
        resources :intervenants do
          resources :document_intervenants
        end
      end
      resources :document_etudes
    end

    resources :selection_intervenants, only: :index do
      resources :postulants, only: :create
    end

    get '/mes_missions', to: 'selection_intervenants#mes_missions', as: 'mes_missions'
    get '/update_mode', to: 'juniors#update_mode', as: 'update_mode'

    resources :clients
    resources :adherents do
      resources :document_adherents
    end

    resources :junior_configurations do
      resources :config_doc_adherents
      resources :config_doc_etudes
      resources :poles
      resources :postes
      resources :permissions
      resources :prestations
      get '/archives', to: 'junior_configurations#archives', as: 'archives'
    end

    resources :tresoreries

    resources :user do
      resources :adherents do
        resources :document_adhesions
      end
    end
  end

  #API V1
  namespace :api, defaults: { format: :json } do
    namespace :v1 do
      resources :etudes, only: [ :index, :show, :update ]
      get '/sessions', to: 'sessions#index', as: 'session'
      get '/userparams', to: 'userparams#index', as: 'userparam'
      get '/userparams/:id', to: 'userparams#update'
    end
  end

  # Sidekiq
  require "sidekiq/web"
  authenticate :user, ->(user) { user.admin? } do
    mount Sidekiq::Web => '/sidekiq'
  end
end

app/models/adherent.rb
class Adherent < ApplicationRecord
  belongs_to :user
  has_many :document_adhesions, dependent: :destroy
  has_many :document_adherents, dependent: :destroy

  has_one_attached :avatar
  delegate :junior, to: :user
end

app/models/client.rb
class Client < ApplicationRecord
  belongs_to :junior
end

app/models/document_etude.rb
class DocumentEtude < ApplicationRecord
  belongs_to :etude

  has_one_attached :document
  has_one_attached :generated_document
end

app/models/document_phase.rb
class DocumentPhase < ApplicationRecord
  belongs_to :phase

  has_one_attached :document
  has_one_attached :generated_document
end

app/models/etude.rb
class Etude < ApplicationRecord
  belongs_to :client, optional: true
  belongs_to :prestation
  belongs_to :charge_etude, class_name: 'User'
  belongs_to :charge_qualite, class_name: 'User', optional: true
  belongs_to :charge_rh, class_name: 'User', optional: true
  belongs_to :junior

  has_many :phases, dependent: :destroy
  has_many :document_etudes, dependent: :destroy
end

app/models/intervenant.rb
class Intervenant < ApplicationRecord
  belongs_to :phase
  belongs_to :user

  has_many :document_intervenants, dependent: :destroy
end

app/models/junior.rb
class Junior < ApplicationRecord
  validates_presence_of :codeje, on: :create, message: "Vous devez avoir un code"
  validates_uniqueness_of :codeje, on: :create, message: "Ce code ne peut être utilisé"

  has_many :users, dependent: :destroy
  has_many :membre_requests, dependent: :destroy
  has_many :membres, through: :membre_requests
  has_many :adherents, through: :users
  has_many :clients, dependent: :destroy
  has_many :etudes, dependent: :destroy
  has_many :phases, through: :etudes

  has_one :junior_configuration
  has_many :config_doc_adherents, through: :junior_configuration
  has_many :poles, through: :junior_configuration
  has_many :postes, through: :junior_configuration
  has_many :permissions, through: :junior_configuration
end

app/models/mandat.rb
class Mandat < ApplicationRecord
  belongs_to :mandat_request
  belongs_to :permission
end

app/models/mandat_request.rb
class MandatRequest < ApplicationRecord
  belongs_to :poste
  belongs_to :pole
  belongs_to :membre

  has_one :mandat, dependent: :destroy
end

app/models/membre.rb
class Membre < ApplicationRecord
  belongs_to :membre_request
  delegate :user, to: :membre_request, allow_nil: true

  has_many :mandat_requests, dependent: :destroy
  has_many :mandats, through: :mandat_requests
  has_many :permissions, through: :mandats
end

app/models/membre_request.rb
class MembreRequest < ApplicationRecord
  belongs_to :junior
  belongs_to :user
  has_one :membre, dependent: :destroy
end

app/models/permission.rb
class Permission < ApplicationRecord
  belongs_to :junior_configuration
end

app/models/phase.rb
class Phase < ApplicationRecord
  belongs_to :etude

  has_one :selection_intervenant, dependent: :destroy
  has_many :intervenants, dependent: :destroy

  has_many :document_phases, dependent: :destroy
end

app/models/pole.rb
class Pole < ApplicationRecord
  belongs_to :junior_configuration
end

app/models/poste.rb
class Poste < ApplicationRecord
  belongs_to :junior_configuration
end

app/models/postulant.rb
class Postulant < ApplicationRecord
  belongs_to :selection_intervenant
  belongs_to :user

  has_many :document_postulants, dependent: :destroy
end

app/models/prestation.rb
class Prestation < ApplicationRecord
  belongs_to :junior_configuration
end

app/models/tresorerie.rb
class Tresorerie < ApplicationRecord
  belongs_to :junior
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  acts_as_token_authenticatable

  belongs_to :junior

  has_one :membre_request, dependent: :destroy
  has_one :userparam, dependent: :destroy
  has_one :membre, through: :membre_request
  has_many :mandat_requests, through: :membre
  has_many :mandats, through: :mandat_requests
  has_many :permissions, through: :mandats
  has_one :adherent, dependent: :destroy
  has_one :document_adhesion, through: :adherent
  has_many :postulants, dependent: :destroy
  has_many :intervenants, dependent: :destroy
end

app/models/userparam.rb
class Userparam < ApplicationRecord
  belongs_to :user
end

app/views/shared/_flashes.html.erb
<% if notice %>
  <div class="alert alert-info alert-dismissible fade show m-1" role="alert">
    <%= notice %>
    <button type="button" class="close" data-dismiss="alert" aria-label="Close">
      <span aria-hidden="true">&times;</span>
    </button>
  </div>
<% end %>
<% if alert %>
  <div class="alert alert-warning alert-dismissible fade show m-1" role="alert">
    <%= alert %>
    <button type="button" class="close" data-dismiss="alert" aria-label="Close">
      <span aria-hidden="true">&times;</span>
    </button>
  </div>
<% end %>

app/views/shared/_navbar.html.erb
<% cookies.encrypted[:navbar_type] = "adherent" if cookies.encrypted[:navbar_type] == nil %>

<div class='navbar'>
  <div class='navbar_logo'>
    <%= image_tag 'HEX_BLEU', style: 'height:4vh; width: auto;'%>
  </div>
  <div class='navbar_links'>
      <%# accueil %>
      <div class='<%= current_page?(junior_path(current_user.junior)) ? "active" : "" %> nav_link'>
        <%= link_to junior_path(current_user.junior_id) do %>Accueil<% end %>
        <div class="<%= current_page?(junior_path(current_user.junior)) ? "active" : "" %> inner">&nbsp;</div>
      </div>
  <%# Menu Membre %>
    <% if cookies.encrypted[:navbar_type] == "membre" && current_user.membre %>
      <%# Etudes %>
      <div class='<%= current_page?(junior_etudes_path(current_user.junior_id)) ? "active" : "" %> nav_link'>
        <%= link_to junior_etudes_path(current_user.junior_id) do %>Etudes<% end %>
        <div class="<%= current_page?(junior_etudes_path(current_user.junior_id)) ? "active" : "" %> inner">&nbsp;</div>
      </div>
      <%# Adherents %>
      <div class='<%= current_page?(junior_adherents_path(current_user.junior_id)) ? "active" : "" %> nav_link'>
        <%= link_to junior_adherents_path(current_user.junior_id) do %>Adhérents<% end %>
        <div class="<%= current_page?(junior_adherents_path(current_user.junior_id)) ? "active" : "" %> inner">&nbsp;</div>
      </div>
      <%# Membres %>
      <div class='<%= current_page?(junior_membres_path(current_user.junior_id)) ? "active" : "" %> nav_link'>
        <%= link_to junior_membres_path(current_user.junior_id) do %>Membres<% end %>
        <div class="<%= current_page?(junior_membres_path(current_user.junior_id)) ? "active" : "" %> inner">&nbsp;</div>
      </div>
      <%# Trésorerie %>
      <div class='<%= current_page?(junior_tresoreries_path(current_user.junior_id)) ? "active" : "" %> nav_link'>
        <%= link_to junior_tresoreries_path(current_user.junior_id) do %>Trésorerie<% end %>
        <div class="<%= current_page?(junior_tresoreries_path(current_user.junior_id)) ? "active" : "" %> inner">&nbsp;</div>
      </div>
      <%# Configuration %>
      <div class='<%= current_page?(edit_junior_junior_configuration_path(current_user.junior_id, current_user.junior.junior_configuration.id)) ? "active" : "" %> nav_link'>
        <%= link_to edit_junior_junior_configuration_path(current_user.junior_id, current_user.junior.junior_configuration.id) do %>Paramètres<% end %>
        <div class="<%= current_page?(edit_junior_junior_configuration_path(current_user.junior_id, current_user.junior.junior_configuration.id)) ? "active" : "" %> inner">&nbsp;</div>
      </div>
    <% end %>

  <%# Menu Adherent %>
    <% if cookies.encrypted[:navbar_type] == "adherent" && current_user.adherent %>
      <%# Nouvelles missions %>
      <div class='<%= current_page?(junior_selection_intervenants_path(current_user.junior_id)) ? "active" : "" %> nav_link'>
        <%= link_to junior_selection_intervenants_path(current_user.junior_id) do %>Nouvelles Missions<% end %>
        <div class="<%= current_page?(junior_selection_intervenants_path(current_user.junior_id)) ? "active" : "" %> inner">&nbsp;</div>
      </div>
      <div class='<%= current_page?(junior_mes_missions_path(current_user.junior_id)) ? "active" : "" %> nav_link'>
        <%= link_to junior_mes_missions_path(current_user.junior_id) do %>Mes Missions<% end %>
        <div class="<%= current_page?(junior_mes_missions_path(current_user.junior_id)) ? "active" : "" %> inner">&nbsp;</div>
      </div>
    <% end %>
  </div>
  <div class='navbar_profile dropdown'>
    <% if current_user.adherent.prenom.nil? && current_user.adherent.nom.nil? %>
      <div class="profile_name"><%= (current_user.email).truncate(33) %></div>
    <% else %>
      <div class="profile_name"><%= (current_user.adherent.prenom + " " + current_user.adherent.nom).truncate(33) %></div>
    <% end %>
    <div class="profile_dropdown dropbtn" id="profile">
      <div class="profile_avatar">
        <% if current_user.adherent.avatar.attached? %><%= image_tag current_user.adherent.avatar.url, class: 'avatar' %> <% else %> <%= image_tag("logo_hex.png", class: 'avatar') %> <% end %>
      </div>
      <i class="fas fa-sort-down"></i>
    </div>
    <div class="drop_content" id="profile">
      <% if cookies.encrypted[:navbar_type] != "membre" && current_user.membre %>
        <div class='line'>
          <%= link_to junior_update_mode_path(current_user.junior, cookies.encrypted[:mode_affichage] = "membre") do %>Mode membre<% end %>
        </div>
      <% end %>
      <% if cookies.encrypted[:navbar_type] != "adherent" && current_user.adherent %>
        <div class='line'>
          <%= link_to junior_update_mode_path(current_user.junior, cookies.encrypted[:mode_affichage] = "adherent") do %>Mode adherent<% end %>
        </div>
      <% end %>
      <div class='line'>
        <% if current_user.membre_request.nil? %>
          <div class='nav_item'>
            <%= link_to junior_membre_requests_path(current_user.junior.id, membre_request: { junior: current_user.junior_id, user: current_user.id }), method: 'post' do %>
              Devenir Membre
            <% end %>
          </div>
        <% end %>
      </div>
      <div class='line'>
        <% if current_user.admin %>
          <div class='nav_item'>
            <%= link_to juniors_path do %>
              Gestion Juniors
            <% end %>
          </div>
        <% end %>
      </div>
      <div class='line'><%= link_to edit_user_registration_path do %>Mon Profil<% end %></div>
      <div class="line"><%= link_to destroy_user_session_path, method: :delete do %>Déconnexion <% end %></div>
      <div class="small_line"><%= "Actuellement en mode " + cookies.encrypted[:navbar_type] %></div>
    </div>
  </div>
</div>

<div id="background_overlay"></div>

app/views/shared/_notification.html.erb
<div class="notif_background">
    <div class="notif_content">
        <div class="notif_number_background notif_number_active">
            <div class="notif_number_num">
                1
            </div>
        </div>
        <div class="notif_icone">
            <i class="fas fa-bell"></i>
        </div>
    </div>
</div>

app/views/shared/rollback.html.erb
<div class='navbar2'>
  <div class='nav_background'>
    <div class="nav_header">
      <div class='logo'> 
        <%= image_tag 'logo_hex', style: 'height:auto;width:4vw;'%> 
      </div>
      <%# Profile Selector - Membre %>
      <div class="profiles">
        <% if current_user.membre.nil? == false %>
          <div class="profile"><i class="fas fa-user"></i><span class="tooltiptext">Espace Adherent</span></div>
          <div class="profile"><i class="fas fa-user-tie"></i><span class="tooltiptext">Espace Membre</span></div>
        <% end %>
        <%# Profile Selector - Admin %>
        <% if current_user.admin? %><div class="profile"><i class="fas fa-user-cog"></i><span class="tooltiptext">Administrateur</span></div><% end %>
      </div>
    </div>

    <%# Navbar - User %>
    <div class='nav_items'>
      <div class='nav_item'><%= link_to junior_selection_intervenants_path(current_user.junior_id) do %><i class="fas fa-search-dollar"></i><% end %></div>
      <% if current_user.membre_request.nil? %><div class='nav_item'><%= link_to junior_membre_requests_path(current_user.junior.id, membre_request: { junior: current_user.junior_id, user: current_user.id }), method: 'post' do %><i class="fas fa-user-plus"></i><% end %></div><% end %>
      <% if current_user.membre_request.nil? == false && current_user.membre_request.status == 'pending' %><div class='nav_item'><i class="fas fa-user-clock"></i></div><% end %>
      <div class='nav_item'><%= link_to edit_user_registration_path do %><% if current_user.adherent.avatar.attached? %><%= image_tag current_user.adherent.avatar.url, class: 'avatar' %> <% else %> <%= image_tag("logo_hex.png", class: 'avatar') %> <% end %></i><% end %><span class="tooltiptext">Mon Profil</span></div>
    </div>
    <%# Navbar - Membre %>
    <div class='nav_items'>
      <div class='nav_item'><%= link_to junior_path(current_user.junior_id) do %><i class="fas fa-home"></i><% end %><span class="tooltiptext">Accueil</span></div>
      <div class='nav_item'><%= link_to junior_etudes_path(current_user.junior_id) do %><i class="fas fa-briefcase"></i><% end %><span class="tooltiptext">JEstion Etudes</span></div>
      <% # <div class='nav_item'><i class="fas fa-project-diagram"></i><span class="tooltiptext">JEstion Projets</span></div> %>
      <div class='nav_item'><%= link_to junior_adherents_path(current_user.junior_id) do %><i class="fas fa-users"></i><% end %><span class="tooltiptext">JEstion Adherents</span></div>
      <div class='nav_item'><%= link_to junior_membres_path(current_user.junior_id) do %><i class="fas fa-user-tie"></i><% end %><span class="tooltiptext">JEstion Membres</span></div>
      <% # <div class='nav_item'><i class="fas fa-chart-bar"></i><span class="tooltiptext">JEstion Indicateurs</span></div> %>
      <% # <div class='nav_item'><i class="fas fa-file-invoice-dollar"></i><span class="tooltiptext">JEstion Trésorerie</span></div> %>
      <% # <div class='nav_item'><i class="fas fa-question-circle"></i><span class="tooltiptext">Support</span></div> %>
      <div class='nav_item'><%= link_to edit_junior_junior_configuration_path(current_user.junior_id, current_user.junior.junior_configuration.id) do %><i class="fas fa-cog"></i><% end %><span class="tooltiptext">Configuration</span></div>
    </div>
    <%# Navbar - Admin %>
    <div class='nav_items'>
    </div>
    <div class="user">
        <div class="logout"><%= link_to destroy_user_session_path, method: :delete do %><i class="fas fa-sign-out-alt"></i><% end %><span class="tooltiptext">Déconnexion</span></div>
    </div>
  </div>
</div>

app/views/template_view/formulaire_template.html.erb
<%= simple_form_for [@junior, @user, @adherent] do |f| %>
    <%= f.error_notification %>
    <div class="formulaire">
        <div class="input">
            <%= f.input :prenom, required: true, autofocus: true, label: 'Prénom' %>
        </div>
        <div class="input">
        </div>
        <div class="input">
        </div>
        <div class="input">
        </div>
    </div>

    <div class="button">
        <%= f.button :submit, "Creer" %>
    </div>
<% end %>

app/views/template_view/menu_template.html.erb
<div class="menu">
  <div class="tabs">
    <div class="tab active">Menu 1</div>
    <div class="tab">Menu 2</div>
    <div class="tab">Menu 3</div>
    <div class="tab">Menu 4</div>
  </div>
  <div class="contents">
    <% # Menu 1 %>
    <div class="content active">      
    </div>

    <% # Menu 2 %>
    <div class="content">
    </div>

    <% # Menu 3 %>
    <div class="content">
    </div>

    <% # Menu 4 %>
    <div class="content">
    </div>
  </div>
</div>

app/views/template_view/modal_template.html.erb
<div class="modal-button" id="id">
    Contenu
</div>

<div class="hex_modal" id="id">
    <div class="background">
        <div class="header">
            <div class="modal-close" id="id">
                <i class="fas fa-times"></i>
            </div>
        </div>
        <div class="content">
            Contenu
        </div>
    </div>
</div>

app/views/template_view/part_reductible.html.erb
<div class="mise_en_page1">
    <div class="part reductible">
        <div class="titre_reducteur">
            <h2>Title</h2>
            <div class="i_reduit"><i class="fas fa-angle-right fa-2x"></i></div>
            <div class="i_developpe"><i class="fas fa-angle-down fa-2x"></i></div>
        </div>
        <div class="content_reducteur">
            Content
        </div>
    </div>
</div>

app/views/template_view/tableau_template.html.erb
<table class="tableau" id="search_tableau">
        <thead class="tabl_header">
            <tr class="header_row">
                <th class="colonne">X</th>
                <th class="colonne">X</th>
                <th class="colonne">X</th>
            </tr>
            <tr class="header_search">
                <th colspan="3" class="search_row"><input type="text" id="tableau_search_bar" placeholder="Recherche"></th>
            </tr>
        </thead>
        <tbody class="tabl_contenu">
            <tr onclick="location.href='<%= lien %>'" class="ligne tabl_search_ligne">
                <td class="colonne" style='color: var(--bleu-hex);'>X</td>
                <td class="colonne" style='color: var(--bleu-hex);'>X</td>
                <td class="colonne"></td>
            </tr>
        </tbody>
</table>