config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: { registrations: 'users/registrations', sessions: 'users/sessions' }
  root to: 'pages#home'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  
  #APP 
  resources :juniors do 
    
    get '/sign_up_step2', to: 'adherents#signup_step2', as: 'signup_step2'
    resources :membre_requests
    
    resources :generated_documents

    resources :membres do
      resources :mandat_requests
      resources :mandats
    end

    resources :etudes do
      resources :phases do
        resources :document_phases
        resources :selection_intervenants, except: :index do
          resources :postulants do
            resources :document_postulants
          end
        end
        resources :intervenants do
          resources :document_intervenants
        end
      end
      resources :document_etudes
    end

    resources :selection_intervenants, only: :index do
      resources :postulants, only: :create
    end

    get '/mes_missions', to: 'selection_intervenants#mes_missions', as: 'mes_missions'
    get '/update_mode', to: 'juniors#update_mode', as: 'update_mode'

    resources :clients
    resources :adherents do
      resources :document_adherents
    end

    resources :junior_configurations do
      resources :config_doc_adherents
      resources :config_doc_etudes
      resources :poles
      resources :postes
      resources :permissions
      resources :prestations
      get '/archives', to: 'junior_configurations#archives', as: 'archives'
    end

    resources :tresoreries

    resources :user do
      resources :adherents do
        resources :document_adhesions
      end
    end
  end

  #API V1
  namespace :api, defaults: { format: :json } do
    namespace :v1 do
      resources :etudes, only: [ :index, :show, :update ]
      get '/sessions', to: 'sessions#index', as: 'session'
      get '/userparams', to: 'userparams#index', as: 'userparam'
      get '/userparams/:id', to: 'userparams#update'
    end
  end

  # Sidekiq
  require "sidekiq/web"
  authenticate :user, ->(user) { user.admin? } do
    mount Sidekiq::Web => '/sidekiq'
  end
end

app/models/adherent.rb
class Adherent < ApplicationRecord
  belongs_to :user
  has_many :document_adhesions, dependent: :destroy
  has_many :document_adherents, dependent: :destroy

  has_one_attached :avatar
  delegate :junior, to: :user
end

app/models/client.rb
class Client < ApplicationRecord
  belongs_to :junior
end

app/models/config_doc_etude.rb
class ConfigDocEtude < ApplicationRecord
  belongs_to :junior_configuration

  has_one_attached :document_type
end

app/models/document_etude.rb
class DocumentEtude < ApplicationRecord
  belongs_to :etude

  has_one_attached :document
  has_one_attached :generated_document
end

app/models/document_phase.rb
class DocumentPhase < ApplicationRecord
  belongs_to :phase

  has_one_attached :document
  has_one_attached :generated_document
end

app/models/etude.rb
class Etude < ApplicationRecord
  belongs_to :client, optional: true
  belongs_to :prestation
  belongs_to :charge_etude, class_name: 'User'
  belongs_to :charge_qualite, class_name: 'User', optional: true
  belongs_to :charge_rh, class_name: 'User', optional: true
  belongs_to :junior

  has_many :phases, dependent: :destroy
  has_many :document_etudes, dependent: :destroy
end

app/models/intervenant.rb
class Intervenant < ApplicationRecord
  belongs_to :phase
  belongs_to :user

  has_many :document_intervenants, dependent: :destroy
end

app/models/junior.rb
class Junior < ApplicationRecord
  validates_presence_of :codeje, on: :create, message: "Vous devez avoir un code"
  validates_uniqueness_of :codeje, on: :create, message: "Ce code ne peut être utilisé"

  has_many :users, dependent: :destroy
  has_many :membre_requests, dependent: :destroy
  has_many :membres, through: :membre_requests
  has_many :adherents, through: :users
  has_many :clients, dependent: :destroy
  has_many :etudes, dependent: :destroy
  has_many :phases, through: :etudes

  has_one :junior_configuration
  has_many :config_doc_adherents, through: :junior_configuration
  has_many :poles, through: :junior_configuration
  has_many :postes, through: :junior_configuration
  has_many :permissions, through: :junior_configuration
end

app/models/mandat.rb
class Mandat < ApplicationRecord
  belongs_to :mandat_request
  belongs_to :permission
end

app/models/mandat_request.rb
class MandatRequest < ApplicationRecord
  belongs_to :poste
  belongs_to :pole
  belongs_to :membre

  has_one :mandat, dependent: :destroy
end

app/models/membre.rb
class Membre < ApplicationRecord
  belongs_to :membre_request
  delegate :user, to: :membre_request, allow_nil: true

  has_many :mandat_requests, dependent: :destroy
  has_many :mandats, through: :mandat_requests
  has_many :permissions, through: :mandats
end

app/models/membre_request.rb
class MembreRequest < ApplicationRecord
  belongs_to :junior
  belongs_to :user
  has_one :membre, dependent: :destroy
end

app/models/permission.rb
class Permission < ApplicationRecord
  belongs_to :junior_configuration
end

app/models/phase.rb
class Phase < ApplicationRecord
  belongs_to :etude

  has_one :selection_intervenant, dependent: :destroy
  has_many :intervenants, dependent: :destroy

  has_many :document_phases, dependent: :destroy
end

app/models/pole.rb
class Pole < ApplicationRecord
  belongs_to :junior_configuration
end

app/models/poste.rb
class Poste < ApplicationRecord
  belongs_to :junior_configuration
end

app/models/postulant.rb
class Postulant < ApplicationRecord
  belongs_to :selection_intervenant
  belongs_to :user

  has_many :document_postulants, dependent: :destroy
end

app/models/prestation.rb
class Prestation < ApplicationRecord
  belongs_to :junior_configuration
end

app/models/tresorerie.rb
class Tresorerie < ApplicationRecord
  belongs_to :junior
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  acts_as_token_authenticatable

  belongs_to :junior

  has_one :membre_request, dependent: :destroy
  has_one :userparam, dependent: :destroy
  has_one :membre, through: :membre_request
  has_many :mandat_requests, through: :membre
  has_many :mandats, through: :mandat_requests
  has_many :permissions, through: :mandats
  has_one :adherent, dependent: :destroy
  has_one :document_adhesion, through: :adherent
  has_many :postulants, dependent: :destroy
  has_many :intervenants, dependent: :destroy
end

app/models/userparam.rb
class Userparam < ApplicationRecord
  belongs_to :user
end

app/controllers/adherents_controller.rb
class AdherentsController < ApplicationController
  before_action :authenticate_user!

  def index
    @adherents = policy_scope(Adherent)
  end

  def signup_step2
    @no_navbar = true
    @user = current_user
    @junior = current_user.junior
    @adherent = current_user.adherent
    authorize @adherent
  end

  def show
    @adherent = Adherent.find(params[:id])
    authorize @adherent
    @user = @adherent.user
    @junior = @user.junior
    @document = DocumentAdhesion.new
    @documents = DocumentAdhesion.where(adherent_id: @adherent.id).order(
      "nom ASC", "date_fin_validite DESC"
    )
    @configuration_id = JuniorConfiguration.find_by(junior_id: @junior.id)
    @document_obligatoires = ConfigDocAdherent.where(junior_configuration_id: @configuration_id, obligatoire: true)
  end

  def edit
    @adherent = Adherent.find(params[:adherent_id])
    @junior = @adherent.user.junior
    authorize @adherent
  end

  def update
    @adherent = Adherent.find(params[:id])
    authorize @adherent
    if @adherent.update(adherent_params)
      flash[:success] = "Object was successfully updated"
      redirect_to edit_user_registration_path
    else
      flash[:error] = "Something went wrong"
      render 'edit'
    end
  end

  private

  def adherent_params
    params.require(:adherent).permit(:id, :nom, :prenom, :telephone, :adresse_postale, :code_postale, :ville,
                                     :niveau_etude, :annee_diplome, :specialisation_etude, :avatar)
  end
end

app/views/adherents/index.html.erb
<table class="tableau" id="search_tableau">
        <thead class="tabl_header">
            <tr class="header_row">
                <th class="colonne"> Nom</th>
                <th class="colonne"> Prénom</th>
                <th class="colonne"> Validité du Dossier</th>
            </tr>
            <tr class="header_search">
                <th colspan="3" class="search_row"><input type="text" id="tableau_search_bar" placeholder="Recherche"></th>
            </tr>
        </thead>
        <tbody class="tabl_contenu">
            <% @adherents.each_with_index do |adherent, index| %>
                <tr onclick="location.href='<%= junior_adherent_path(adherent.junior, adherent) %>'" class="ligne tabl_search_ligne">
                        <td class="colonne adherent_tag" id='nom' style='color: var(--bleu-hex);'> <%= adherent.nom %></td>
                        <td class="colonne adherent_tag" id='prenom' style='color: var(--bleu-hex);'> <%= adherent.prenom %></td>
                        <td class="colonne" id='validite'>
                            <% if adherent.file_status == 'valid' %>
                                <div class="valid" style='color: var(--vert)'>Dossier valide</div>
                            <% elsif adherent.file_status == 'invalid' %>
                                <div class="invalid" style='color: var(--rouge)'>Dossier invalide</div>
                            <% elsif adherent.file_status == 'pending' %>
                                <div class="pending" style='color: var(--jaune)'>En attente de validation</div>
                            <% end %>
                        </td>
                </tr>
            <% end %>
        </tbody>
</table>

<%# adherent_tag_ %>

app/views/adherents/signup_step2.html.erb
<div class="session_background">
  <%= simple_form_for [current_user.junior, current_user.adherent] do |f| %>
    <div class="content_div">
      <div class="content_background">
        <div class="content_main">
          <div class="main_title">
            <div class="title_line">Parle-nous</div>
            <div class="title_line">un peu de toi !</div>
          </div>
          <div class="main_form">
            <div class="form_input_line">
                <%= f.input :prenom,
                          required: true,
                          label: false,
                          placeholder: "Prénom",
                          input_html: { class: 'form_input' } %>
            </div>
            <div class="form_input_line">
                <%= f.input :nom,
                          required: true,
                          label: false,
                          placeholder: "Nom",
                          input_html: { class: 'form_input' } %>
            </div>
            <div class="form_input_line">
                <%= f.input :telephone,
                          label: false,
                          placeholder: "Téléphone",
                          input_html: { class: 'form_input' } %>
            </div>
            <div class="form_input_line">
                <%= f.input :niveau_etude,
                          required: true,
                          label: false,
                          include_blank: "Niveau d'étude",
                          selected: "Niveau d'étude",
                          collection: @junior.junior_configuration.niveau_etude,
                          label_method: lambda { |niveau_etude| "#{niveau_etude}" },
                          input_html: { class: 'form_input' } %>
            </div>
            <div class="form_input_line">
                <%= f.input :specialisation_etude,
                          required: true,
                          label: false,
                          include_blank: "Spécialisation d'étude",
                          selected: "Spécialisation d'étude",
                          collection: @junior.junior_configuration.specialisation_etude,
                          label_method: lambda { |spe| "#{spe}" },
                          input_html: { class: 'form_input' } %>
            </div>
            <div class="form_input_line">
                <%= f.input :annee_diplome,
                          required: true,
                          label: false,
                          as: :numeric,
                          placeholder: "Année d'obtention du diplôme",
                          input_html: { min: Date.today.year,class: 'form_input' } %>
            </div>
            <div class="form_btn">
              <%= f.button :button do %>
                <span class="circle_arrow1"><i class="fas fa-arrow-right"></i></span>
                Continuer
              <% end %>
            </div>
          </div>
        </div>
        <div class="content_footer">
          <div class="footer_links">
          </div>
          <div class="footer_logo">
            <%= image_tag 'HEX_BLANC', style: 'height:10vh; width: auto;'%>
          </div>
        </div>
      </div>
    </div>
  <% end %>
</div>