config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: { registrations: 'users/registrations', sessions: 'users/sessions' }
  root to: 'pages#home'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  
  #APP 
  resources :juniors do 
    
    get '/sign_up_step2', to: 'adherents#signup_step2', as: 'signup_step2'
    resources :membre_requests
    
    resources :generated_documents

    resources :membres do
      resources :mandat_requests
      resources :mandats
    end

    resources :etudes do
      resources :phases do
        resources :document_phases
        resources :selection_intervenants, except: :index do
          resources :postulants do
            resources :document_postulants
          end
        end
        resources :intervenants do
          resources :document_intervenants
        end
      end
      resources :document_etudes
    end

    resources :selection_intervenants, only: :index do
      resources :postulants, only: :create
    end

    get '/mes_missions', to: 'selection_intervenants#mes_missions', as: 'mes_missions'
    get '/update_mode', to: 'juniors#update_mode', as: 'update_mode'

    resources :clients
    resources :adherents do
      resources :document_adherents
    end

    resources :junior_configurations do
      resources :config_doc_adherents
      resources :config_doc_etudes
      resources :poles
      resources :postes
      resources :permissions
      resources :prestations
      get '/archives', to: 'junior_configurations#archives', as: 'archives'
    end

    resources :tresoreries

    resources :user do
      resources :adherents do
        resources :document_adhesions
      end
    end
  end

  #API V1
  namespace :api, defaults: { format: :json } do
    namespace :v1 do
      resources :etudes, only: [ :index, :show, :update ]
      get '/sessions', to: 'sessions#index', as: 'session'
      get '/userparams', to: 'userparams#index', as: 'userparam'
      get '/userparams/:id', to: 'userparams#update'
    end
  end

  # Sidekiq
  require "sidekiq/web"
  authenticate :user, ->(user) { user.admin? } do
    mount Sidekiq::Web => '/sidekiq'
  end
end

app/models/etude.rb
class Etude < ApplicationRecord
  belongs_to :client, optional: true
  belongs_to :prestation
  belongs_to :charge_etude, class_name: 'User'
  belongs_to :charge_qualite, class_name: 'User', optional: true
  belongs_to :charge_rh, class_name: 'User', optional: true
  belongs_to :junior

  has_many :phases, dependent: :destroy
  has_many :document_etudes, dependent: :destroy
end

app/controllers/etudes_controller.rb
class EtudesController < ApplicationController
  before_action :authenticate_user!

  def index
    @etudes = policy_scope(Etude)
  end

  def show
    @etude = Etude.find(params[:id])
    @junior = @etude.junior
    @new_client = Client.new
    @phases = @etude.phases.order("date_debut ASC")
    @document_etudes = @etude.document_etudes.order("date_signature ASC")
    @etapes = order_by_date(@phases, @document_etudes)
    @new_phase = Phase.new
    authorize @etude
  end

  def new
    @junior = Junior.find(junior_id_params)
    @etude = Etude.new
    authorize @etude
    @new_reference = new_ref_calculation
  end

  def create
    @junior = Junior.find(junior_id_params)
    @etude = Etude.new(etude_params)
    @etude.junior = @junior
    authorize @etude
    if @etude.save
      flash[:success] = "Object successfully created"
      redirect_to junior_etude_path(@junior, @etude)
    else
      flash[:error] = "Something went wrong"
      render junior_etude_path(@junior, @etude)
    end
  end

  def update
    @etude = Etude.find(params[:id])
    @junior = Junior.find(junior_id_params)
    authorize @etude
    if etude_params[:client] == "remove"
      @etude.update(client: nil)
      redirect_to junior_etude_path(@junior, @etude)
    elsif @etude.update(etude_params)
      flash[:success] = "Etude was successfully updated"
      redirect_to junior_etude_path(@junior, @etude)
    else
      flash[:error] = "Something went wrong"
      render junior_etude_path(@junior, @etude)
    end
  end

  def destroy
    @etude = Etude.find(params[:id])
    authorize @etude
    if @etude.destroy
      flash[:success] = 'Etude was successfully deleted.'
      redirect_to etudes_url
    else
      flash[:error] = 'Something went wrong'
      redirect_to etudes_url
    end
  end

  private

  def etude_params
    params.require(:etude).permit!
  end

  def junior_id_params
    params.require(:junior_id)
  end

  def new_ref_calculation
    if @etudes.nil?
      Date.today.strftime("%y") + "001"
    elsif @etudes.order(:ref_etude).last
      @etudes.order(:ref_etude).last.ref_etude.to_i + 1
    else
      Date.today.strftime("%y") + "001"
    end
  end

  def order_by_date(phases, docs)
    etapes = phases + docs
    resultat = []
    etapes.each do |etape|
      date = nil
      case etape.class.to_s
      when "Phase"
        etape.date_debut.nil? ? date = etape.created_at : date = etape.date_debut
      when "DocumentEtude"
        etape.date_signature.nil? ? date = etape.created_at : date = etape.date_signature
      end
      resultat << { date: date, etape: etape }
    end
    return resultat.sort_by! { |etape| etape[:date] }
  end
end

app/views/etudes/index.html.erb
<div class="lien_bleu"><%= link_to new_junior_etude_path(current_user.junior_id) do %>Ajouter une étude<% end %></div>
    <table class="tableau" id="search_tableau">
    <thead class="tabl_header">
        <tr class="header_row">
        <th class="colonne"> Reference étude</th>
        <th class="colonne"> Date de signature</th>
        <th class="colonne"> Date de début d'étude</th>
        <th class="colonne"> prestation</th>
        <th class="colonne"> Statut</th>
        </tr>
        <tr class="header_search">
            <th colspan="5" class="search_row"><input type="text" id="tableau_search_bar" placeholder="Recherche"></th>
        </tr>
    </thead>     
    <tbody class="modal_buttons tabl_contenu">
        <% @etudes.each_with_index do |etude, index| %>
            <tr onclick="location.href='<%= junior_etude_path(etude.junior, etude) %>'" class="ligne tabl_search_ligne">
                <td class="colonne"> <%= etude.ref_etude %></td>
                <td class="colonne"> <%= etude.date_debut.strftime("%d-%m-%Y") %></td>
                <td class="colonne"> <%= etude.date_signature.nil? ? "N/A" : etude.date_signature.strftime("%d-%m-%Y") %></td>
                <td class="colonne"> <%= etude.prestation.nom %></td>
                <td class="colonne"> <%= etude.statut %></td>
            </tr>
        <% end %>
    </tbody>
    </table>
</div>

app/views/etudes/new.html.erb
<%= render 'etudes/shared/forms' %>